# Generated by Django 2.2.8 on 2020-07-10 13:18

import datetime
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AnimalBreed',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=256, verbose_name='Порода')),
                ('code', models.CharField(max_length=16, verbose_name='Краткий код породы')),
            ],
        ),
        migrations.CreateModel(
            name='AnimalKind',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=256, verbose_name='Вид животного')),
                ('code', models.CharField(max_length=16, verbose_name='Краткий код вида')),
            ],
        ),
        migrations.CreateModel(
            name='Pet',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100, verbose_name='Кличка')),
                ('description', models.TextField(verbose_name='Описание')),
                ('coming_date', models.DateField(default=datetime.date.today, verbose_name='Дата поступления')),
                ('condition', models.IntegerField(choices=[(10, 'Хорошее'), (20, 'Удовлетворительное'), (30, 'Плохое')], verbose_name='Состояние животного')),
                ('photo', models.ImageField(blank=True, upload_to='pets_photo', verbose_name='Фото животного')),
                ('breed', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pet.AnimalBreed', verbose_name='Вид и порода')),
            ],
        ),
        migrations.AddField(
            model_name='animalbreed',
            name='kind',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pet.AnimalKind', verbose_name='Вид'),
        ),
    ]
