# Generated by Django 2.2.8 on 2020-07-13 06:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pet', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='animalbreed',
            name='code',
        ),
        migrations.RemoveField(
            model_name='animalkind',
            name='code',
        ),
    ]
